// Theme Type Constants
export const THEME_TYPE_LITE = 'THEME_TYPE_LITE';
export const THEME_TYPE_SEMI_DARK = 'THEME_TYPE_SEMI_DARK';
export const THEME_TYPE_DARK = 'THEME_TYPE_DARK';

// Layout Type Constants
export const LAYOUT_TYPE_BOXED = 'LAYOUT_TYPE_BOXED';
export const LAYOUT_TYPE_FRAMED = 'LAYOUT_TYPE_FRAMED';
export const LAYOUT_TYPE_FULL = 'LAYOUT_TYPE_FULL';

// Nav Style Constants
export const NAV_STYLE_VERTICAL_FIXED = 'NAV_STYLE_VERTICAL_FIXED';
export const NAV_STYLE_VERTICAL_MINI_SIDEBAR = 'NAV_STYLE_VERTICAL_MINI_SIDEBAR';
export const NAV_STYLE_VERTICAL_DRAWER = 'NAV_STYLE_VERTICAL_DRAWER';
export const NAV_STYLE_HORIZONTAL_DARK = 'NAV_STYLE_HORIZONTAL_DARK';
export const NAV_STYLE_HORIZONTAL_LIGHT = 'NAV_STYLE_HORIZONTAL_LIGHT';
export const NAV_STYLE_HORIZONTAL_INSIDE = 'NAV_STYLE_HORIZONTAL_INSIDE';
export const NAV_STYLE_HORIZONTAL_BOTTOM = 'NAV_STYLE_HORIZONTAL_BOTTOM';
export const NAV_STYLE_HORIZONTAL_TOP = 'NAV_STYLE_HORIZONTAL_TOP';

// Tab Constants
export const TAB_BREAKPOINT = 992;
